// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.protos

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the protos package it is being compiled against.
// A compilation error at this line likely means your copy of the
// protos package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the protos package

type RequestLogin struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Userpsd              string   `protobuf:"bytes,2,opt,name=userpsd,proto3" json:"userpsd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestLogin) Reset()         { *m = RequestLogin{} }
func (m *RequestLogin) String() string { return proto.CompactTextString(m) }
func (*RequestLogin) ProtoMessage()    {}
func (*RequestLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *RequestLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestLogin.Unmarshal(m, b)
}
func (m *RequestLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestLogin.Marshal(b, m, deterministic)
}
func (m *RequestLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestLogin.Merge(m, src)
}
func (m *RequestLogin) XXX_Size() int {
	return xxx_messageInfo_RequestLogin.Size(m)
}
func (m *RequestLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RequestLogin proto.InternalMessageInfo

func (m *RequestLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RequestLogin) GetUserpsd() string {
	if m != nil {
		return m.Userpsd
	}
	return ""
}

type ResponseLogin struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseLogin) Reset()         { *m = ResponseLogin{} }
func (m *ResponseLogin) String() string { return proto.CompactTextString(m) }
func (*ResponseLogin) ProtoMessage()    {}
func (*ResponseLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *ResponseLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseLogin.Unmarshal(m, b)
}
func (m *ResponseLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseLogin.Marshal(b, m, deterministic)
}
func (m *ResponseLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseLogin.Merge(m, src)
}
func (m *ResponseLogin) XXX_Size() int {
	return xxx_messageInfo_ResponseLogin.Size(m)
}
func (m *ResponseLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseLogin proto.InternalMessageInfo

func (m *ResponseLogin) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ResponseLogin) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RequestChat struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestChat) Reset()         { *m = RequestChat{} }
func (m *RequestChat) String() string { return proto.CompactTextString(m) }
func (*RequestChat) ProtoMessage()    {}
func (*RequestChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

func (m *RequestChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestChat.Unmarshal(m, b)
}
func (m *RequestChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestChat.Marshal(b, m, deterministic)
}
func (m *RequestChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestChat.Merge(m, src)
}
func (m *RequestChat) XXX_Size() int {
	return xxx_messageInfo_RequestChat.Size(m)
}
func (m *RequestChat) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestChat.DiscardUnknown(m)
}

var xxx_messageInfo_RequestChat proto.InternalMessageInfo

func (m *RequestChat) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestChat) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ResponseChat struct {
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseChat) Reset()         { *m = ResponseChat{} }
func (m *ResponseChat) String() string { return proto.CompactTextString(m) }
func (*ResponseChat) ProtoMessage()    {}
func (*ResponseChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{3}
}

func (m *ResponseChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseChat.Unmarshal(m, b)
}
func (m *ResponseChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseChat.Marshal(b, m, deterministic)
}
func (m *ResponseChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseChat.Merge(m, src)
}
func (m *ResponseChat) XXX_Size() int {
	return xxx_messageInfo_ResponseChat.Size(m)
}
func (m *ResponseChat) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseChat.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseChat proto.InternalMessageInfo

func (m *ResponseChat) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestLogin)(nil), "protocol.RequestLogin")
	proto.RegisterType((*ResponseLogin)(nil), "protocol.ResponseLogin")
	proto.RegisterType((*RequestChat)(nil), "protocol.RequestChat")
	proto.RegisterType((*ResponseChat)(nil), "protocol.ResponseChat")
}

func init() { proto.RegisterFile("protocol.protos", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x03, 0x33, 0x84, 0x38, 0x60, 0x7c, 0x25, 0x17, 0x2e, 0x9e, 0xa0,
	0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x9f, 0xfc, 0xf4, 0xcc, 0x3c, 0x21, 0x29, 0x2e, 0x8e, 0xd2,
	0xe2, 0xd4, 0xa2, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x5f,
	0x48, 0x82, 0x8b, 0x1d, 0xc4, 0x2e, 0x28, 0x4e, 0x91, 0x60, 0x02, 0x4b, 0xc1, 0xb8, 0x4a, 0x96,
	0x5c, 0xbc, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x10, 0x63, 0xc4, 0xb8, 0xd8, 0x8a,
	0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0xc1, 0x86, 0xb0, 0x06, 0x41, 0x79, 0x42, 0x02, 0x5c, 0xcc, 0xb9,
	0xc5, 0xe9, 0x50, 0xed, 0x20, 0xa6, 0x92, 0x21, 0x17, 0x37, 0xd4, 0x01, 0xce, 0x19, 0x89, 0x25,
	0x20, 0x05, 0xa5, 0x99, 0x29, 0x50, 0xab, 0x41, 0x4c, 0x2c, 0x5a, 0x14, 0x40, 0x6e, 0x86, 0xd8,
	0x06, 0xd3, 0x83, 0xaa, 0x22, 0x89, 0x0d, 0xec, 0x3f, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xc8, 0xa5, 0xab, 0x44, 0xf8, 0x00, 0x00, 0x00,
}
