// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logger.pb

package loggersvr

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request 请求数据格式
type Request struct {
	ServerId             int32    `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	ServerTag            string   `protobuf:"bytes,2,opt,name=serverTag,proto3" json:"serverTag,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfbdaed7bfc6b1a9, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *Request) GetServerTag() string {
	if m != nil {
		return m.ServerTag
	}
	return ""
}

func (m *Request) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// Response 响应数据格式
type Response struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfbdaed7bfc6b1a9, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "loggersvr.Request")
	proto.RegisterType((*Response)(nil), "loggersvr.Response")
}

func init() { proto.RegisterFile("logger.pb", fileDescriptor_cfbdaed7bfc6b1a9) }

var fileDescriptor_cfbdaed7bfc6b1a9 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0xb1, 0x0b, 0x82, 0x40,
	0x14, 0x87, 0x33, 0xc9, 0xf4, 0xb5, 0xc4, 0x0b, 0x42, 0xa4, 0x41, 0x6e, 0x72, 0x72, 0xa8, 0xa5,
	0xb9, 0x2d, 0x68, 0x3a, 0x8a, 0x66, 0xa5, 0xc7, 0x11, 0x54, 0x67, 0xef, 0x9d, 0xfe, 0xfd, 0x91,
	0x1e, 0x46, 0xdb, 0xef, 0xfb, 0x86, 0x1f, 0x1f, 0x24, 0x0f, 0x6b, 0x0c, 0x71, 0xd9, 0xd4, 0xe8,
	0xa7, 0x74, 0xac, 0x2e, 0x30, 0xd7, 0xf4, 0x6e, 0x49, 0x1c, 0x66, 0x10, 0x0b, 0x71, 0x47, 0x7c,
	0xbc, 0xa5, 0x41, 0x1e, 0x14, 0x33, 0x3d, 0x32, 0x6e, 0x20, 0x19, 0xf6, 0xb9, 0x32, 0xe9, 0x34,
	0x0f, 0x8a, 0x44, 0xff, 0x04, 0x2e, 0x21, 0x7c, 0x8a, 0x49, 0xc3, 0xde, 0x7f, 0xa7, 0x52, 0x10,
	0x6b, 0x92, 0xc6, 0xbe, 0x84, 0x70, 0x0d, 0x91, 0xb8, 0xca, 0xb5, 0xe2, 0x5f, 0x3d, 0x6d, 0x0f,
	0x10, 0x9d, 0xfa, 0x0e, 0xdc, 0xc3, 0xe2, 0xca, 0x77, 0x47, 0x1e, 0xb1, 0x1c, 0xfb, 0x4a, 0x1f,
	0x97, 0xad, 0xfe, 0xdc, 0xf0, 0xac, 0x26, 0x75, 0xd4, 0xb0, 0x75, 0x76, 0xf7, 0x09, 0x00, 0x00,
	0xff, 0xff, 0xae, 0x52, 0x38, 0x9e, 0xdd, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoggerClient is the client API for Logger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggerClient interface {
	WriteLogger(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type loggerClient struct {
	cc *grpc.ClientConn
}

func NewLoggerClient(cc *grpc.ClientConn) LoggerClient {
	return &loggerClient{cc}
}

func (c *loggerClient) WriteLogger(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/loggersvr.Logger/WriteLogger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerServer is the server API for Logger service.
type LoggerServer interface {
	WriteLogger(context.Context, *Request) (*Response, error)
}

func RegisterLoggerServer(s *grpc.Server, srv LoggerServer) {
	s.RegisterService(&_Logger_serviceDesc, srv)
}

func _Logger_WriteLogger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).WriteLogger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loggersvr.Logger/WriteLogger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).WriteLogger(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Logger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "loggersvr.Logger",
	HandlerType: (*LoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteLogger",
			Handler:    _Logger_WriteLogger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logger.pb",
}
