// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.pb

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestLogin struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Userpsd              string   `protobuf:"bytes,2,opt,name=userpsd,proto3" json:"userpsd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestLogin) Reset()         { *m = RequestLogin{} }
func (m *RequestLogin) String() string { return proto.CompactTextString(m) }
func (*RequestLogin) ProtoMessage()    {}
func (*RequestLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_a16c9b51ab9bc514, []int{0}
}

func (m *RequestLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestLogin.Unmarshal(m, b)
}
func (m *RequestLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestLogin.Marshal(b, m, deterministic)
}
func (m *RequestLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestLogin.Merge(m, src)
}
func (m *RequestLogin) XXX_Size() int {
	return xxx_messageInfo_RequestLogin.Size(m)
}
func (m *RequestLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RequestLogin proto.InternalMessageInfo

func (m *RequestLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RequestLogin) GetUserpsd() string {
	if m != nil {
		return m.Userpsd
	}
	return ""
}

type ResponseLogin struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseLogin) Reset()         { *m = ResponseLogin{} }
func (m *ResponseLogin) String() string { return proto.CompactTextString(m) }
func (*ResponseLogin) ProtoMessage()    {}
func (*ResponseLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_a16c9b51ab9bc514, []int{1}
}

func (m *ResponseLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseLogin.Unmarshal(m, b)
}
func (m *ResponseLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseLogin.Marshal(b, m, deterministic)
}
func (m *ResponseLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseLogin.Merge(m, src)
}
func (m *ResponseLogin) XXX_Size() int {
	return xxx_messageInfo_ResponseLogin.Size(m)
}
func (m *ResponseLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseLogin proto.InternalMessageInfo

func (m *ResponseLogin) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ResponseLogin) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RequestChat struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestChat) Reset()         { *m = RequestChat{} }
func (m *RequestChat) String() string { return proto.CompactTextString(m) }
func (*RequestChat) ProtoMessage()    {}
func (*RequestChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_a16c9b51ab9bc514, []int{2}
}

func (m *RequestChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestChat.Unmarshal(m, b)
}
func (m *RequestChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestChat.Marshal(b, m, deterministic)
}
func (m *RequestChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestChat.Merge(m, src)
}
func (m *RequestChat) XXX_Size() int {
	return xxx_messageInfo_RequestChat.Size(m)
}
func (m *RequestChat) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestChat.DiscardUnknown(m)
}

var xxx_messageInfo_RequestChat proto.InternalMessageInfo

func (m *RequestChat) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestChat) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ResponseChat struct {
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseChat) Reset()         { *m = ResponseChat{} }
func (m *ResponseChat) String() string { return proto.CompactTextString(m) }
func (*ResponseChat) ProtoMessage()    {}
func (*ResponseChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_a16c9b51ab9bc514, []int{3}
}

func (m *ResponseChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseChat.Unmarshal(m, b)
}
func (m *ResponseChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseChat.Marshal(b, m, deterministic)
}
func (m *ResponseChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseChat.Merge(m, src)
}
func (m *ResponseChat) XXX_Size() int {
	return xxx_messageInfo_ResponseChat.Size(m)
}
func (m *ResponseChat) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseChat.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseChat proto.InternalMessageInfo

func (m *ResponseChat) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestLogin)(nil), "protocol.RequestLogin")
	proto.RegisterType((*ResponseLogin)(nil), "protocol.ResponseLogin")
	proto.RegisterType((*RequestChat)(nil), "protocol.RequestChat")
	proto.RegisterType((*ResponseChat)(nil), "protocol.ResponseChat")
}

func init() { proto.RegisterFile("protocol.pb", fileDescriptor_a16c9b51ab9bc514) }

var fileDescriptor_a16c9b51ab9bc514 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x2b, 0x48, 0x12, 0xe2, 0x80, 0x71, 0x94, 0x5c, 0xb8, 0x78, 0x82,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x7c, 0xf2, 0xd3, 0x33, 0xf3, 0x84, 0xa4, 0xb8, 0x38, 0x4a,
	0x8b, 0x53, 0x8b, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c,
	0x21, 0x09, 0x2e, 0x76, 0x10, 0xbb, 0xa0, 0x38, 0x45, 0x82, 0x09, 0x2c, 0x05, 0xe3, 0x2a, 0x59,
	0x72, 0xf1, 0x06, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x42, 0x8c, 0x11, 0xe3, 0x62, 0x2b,
	0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x06, 0x1b, 0xc2, 0x1a, 0x04, 0xe5, 0x09, 0x09, 0x70, 0x31, 0xe7,
	0x16, 0xa7, 0x43, 0xb5, 0x83, 0x98, 0x4a, 0x86, 0x5c, 0xdc, 0x50, 0x07, 0x38, 0x67, 0x24, 0x96,
	0x80, 0x14, 0x94, 0x66, 0xa6, 0x40, 0xad, 0x06, 0x31, 0xb1, 0x68, 0x51, 0x00, 0xb9, 0x19, 0x62,
	0x1b, 0x4c, 0x0f, 0xaa, 0x8a, 0x24, 0x36, 0xb0, 0xff, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xaa, 0xb3, 0x35, 0xba, 0xf5, 0x00, 0x00, 0x00,
}
